// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package text_processor_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TextProcessorServiceClient is the client API for TextProcessorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextProcessorServiceClient interface {
	GetTopTenUsedWords(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type textProcessorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextProcessorServiceClient(cc grpc.ClientConnInterface) TextProcessorServiceClient {
	return &textProcessorServiceClient{cc}
}

func (c *textProcessorServiceClient) GetTopTenUsedWords(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/textprocessor.TextProcessorService/GetTopTenUsedWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextProcessorServiceServer is the server API for TextProcessorService service.
// All implementations must embed UnimplementedTextProcessorServiceServer
// for forward compatibility
type TextProcessorServiceServer interface {
	GetTopTenUsedWords(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedTextProcessorServiceServer()
}

// UnimplementedTextProcessorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTextProcessorServiceServer struct {
}

func (UnimplementedTextProcessorServiceServer) GetTopTenUsedWords(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopTenUsedWords not implemented")
}
func (UnimplementedTextProcessorServiceServer) mustEmbedUnimplementedTextProcessorServiceServer() {}

// UnsafeTextProcessorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextProcessorServiceServer will
// result in compilation errors.
type UnsafeTextProcessorServiceServer interface {
	mustEmbedUnimplementedTextProcessorServiceServer()
}

func RegisterTextProcessorServiceServer(s grpc.ServiceRegistrar, srv TextProcessorServiceServer) {
	s.RegisterService(&TextProcessorService_ServiceDesc, srv)
}

func _TextProcessorService_GetTopTenUsedWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextProcessorServiceServer).GetTopTenUsedWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/textprocessor.TextProcessorService/GetTopTenUsedWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextProcessorServiceServer).GetTopTenUsedWords(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// TextProcessorService_ServiceDesc is the grpc.ServiceDesc for TextProcessorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextProcessorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "textprocessor.TextProcessorService",
	HandlerType: (*TextProcessorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopTenUsedWords",
			Handler:    _TextProcessorService_GetTopTenUsedWords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "text-processor.proto",
}
